# Matrix Demo
In this notebook, some Matrix operations are done and shows agreement in forward/backward passes with PyTorch.

In [1]:
import torch
from matprop.engine import Matrix

In [2]:
m1 = Matrix([[1, 2], [2, 1]])
m2 = Matrix([[2, 1], [1, 2]])
m1

Matrix(
data=
[[1. 2.]
 [2. 1.]]
grad=
[[0. 0.]
 [0. 0.]]
)

In [3]:
m3 = m1 + m2
m3

Matrix(
data=
[[3. 3.]
 [3. 3.]]
grad=
[[0. 0.]
 [0. 0.]]
)

In [4]:
m3._prev

{Matrix(
 data=
 [[1. 2.]
  [2. 1.]]
 grad=
 [[0. 0.]
  [0. 0.]]
 ),
 Matrix(
 data=
 [[2. 1.]
  [1. 2.]]
 grad=
 [[0. 0.]
  [0. 0.]]
 )}

In [5]:
A = torch.Tensor([[1., 2.]])
A.requires_grad = True

B = torch.Tensor([[3., 2.],
                  [2., 1.]])
B.requires_grad = True

AB = A @ B
AB.retain_grad()

AB2 = AB ** 3
AB2.retain_grad()

Relu = AB2.relu()
Relu.retain_grad()

Sum = Relu.sum()
Sum.retain_grad()

Sum

tensor(407., grad_fn=<SumBackward0>)

In [6]:
Sum.backward(retain_graph=True)
A.grad, B.grad, AB.grad, AB2.grad, Relu.grad, Sum.grad

(tensor([[537., 342.]]),
 tensor([[147.,  48.],
         [294.,  96.]]),
 tensor([[147.,  48.]]),
 tensor([[1., 1.]]),
 tensor([[1., 1.]]),
 tensor(1.))

In [7]:
A = Matrix([[1., 2.]])

B = Matrix([[3., 2.],
            [2., 1.]])

AB = A @ B

AB2 = AB ** 3

Relu = AB2.relu()

Sum = Relu.sum()

Sum

Matrix(
data=
407.0
grad=
0.0
)

In [8]:
Sum.backward()
A.grad, B.grad, AB.grad, AB2.grad, Relu.grad, Sum.grad

(array([[537., 342.]], dtype=float32),
 array([[147.,  48.],
        [294.,  96.]], dtype=float32),
 array([[147.,  48.]], dtype=float32),
 array([[1., 1.]], dtype=float32),
 array([[1., 1.]], dtype=float32),
 array([[1.]]))

In [9]:
A = torch.Tensor([[1.],
                  [2.]])
A.requires_grad = True

AT = A.T
AT.retain_grad()

B = torch.Tensor([[3., 2.],
                  [2., 1.]])
B.requires_grad = True

AB = AT @ B
AB.retain_grad()

C = torch.tensor([[1., 1.]])
C.requires_grad = True

ABPlusC = AB + C
ABPlusC.retain_grad()

Sum = ABPlusC.sum()
Sum.retain_grad()

Sum

tensor(13., grad_fn=<SumBackward0>)

In [10]:
Sum.backward(retain_graph=True)
A.grad, AT.grad, B.grad, AB.grad, ABPlusC.grad, Sum.grad

(tensor([[5.],
         [3.]]),
 tensor([[5., 3.]]),
 tensor([[1., 1.],
         [2., 2.]]),
 tensor([[1., 1.]]),
 tensor([[1., 1.]]),
 tensor(1.))

In [11]:
A = Matrix([[1.],
            [2.]])

AT = A.transpose()

B = Matrix([[3., 2.],
            [2., 1.]])

AB = AT @ B

C = Matrix([[1., 1.]])

ABPlusC = AB + C

Sum = ABPlusC.sum()

Sum

Matrix(
data=
13.0
grad=
0.0
)

In [12]:
Sum.backward()
A.grad, AT.grad, B.grad, AB.grad, ABPlusC.grad, Sum.grad

(array([[5.],
        [3.]], dtype=float32),
 array([[5., 3.]], dtype=float32),
 array([[1., 1.],
        [2., 2.]], dtype=float32),
 array([[1., 1.]], dtype=float32),
 array([[1., 1.]], dtype=float32),
 array([[1.]]))